[package]
name = "passgen"
version = "0.1.3"
edition = "2021"
author = "Vladimir N Platonov"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
base64 = "~0.5.0"